version: '3'

services:
  web:
    build: .
    ports:
      - '5000:5000'
    command: pipenv run prd
  cron:
    build: .
    environment:
      - FLASK_APP=flask_template
      - FLASK_ENV=production
    command: pipenv run cron
  celery:
    build: .
    environment:
      - C_FORCE_ROOT=1
      - FLASK_APP=flask_template
      - FLASK_ENV=production
    command: pipenv run celery
